# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 508f38316f5c16e812fd6a11e96062ba2d7725f03c2bca45b445dd01b97918c02776a77d54c36defb9e2917817006a359d82e1e176a6fedf85a1c60f6b1b3421

test:
  secret_key_base: 4bdfbbf2b0e58ffeb6e9e272a150955cba5c95f738de14a5d08be542a6666f1969621ae90268ccf4d9074ced4bbc69781edc3022aac087b090e82454fe6224c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
